<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="4.150.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="4.150.1" />
    <PackageReference Include="PDFtoImage" Version="5.4.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../PrintAI.Domain/PrintAI.Domain.csproj" />
    <ProjectReference Include="../PrintAI.ImageDecoding/PrintAI.ImageDecoding.csproj" />
    <ProjectReference Include="../PrintAI.Layout/PrintAI.Layout.csproj" />
  </ItemGroup>
</Project>
